# Keep this aligned with servers.json and .env

airflow:
  connections:
    - conn_id: postgres_default
      conn_type: postgres
      conn_host: postgres
      conn_schema: public
      conn_login: 
      conn_password: 
      conn_port: 
  # pools:
  #   - pool_name:
  #     pool_slot:
  #     pool_description:
  # variables:
  #   - variable_name:
  #     variable_value:
